apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: ns-test
  labels:
    app: go_project-service
    appName: go_project-service
  name: go_project-service
spec:
  type: NodePort
  ports:
    - name: go_project-service
      port: 8100    #服务(svc) 访问端口
      protocol: TCP
      targetPort: 3001 # pod （容器）端口
      nodePort: 30011 # pod （容器）端口
  selector:
    app: go_project
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns-test
  name: go_project-deployment
  labels:     # 自定义资源的标签
    app: web2
    appName: go_project-web2
    version: {{APP_VERSION}}
spec:
  selector:
    matchLabels:
      app: go_project
      appName: nginx-web
  replicas: 2
  template:
    metadata:
      labels:
        app: go_project
        appName: go_project-web
    spec:
      containers:
        - name: go
          image: {{IMG_NAME}}
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 200Mi
          ports:
            - containerPort: 80