pipeline {
    agent any
    stages {
        stage("build images") {
            steps{
                echo "----------------------生产docker镜像------------------"
                sh '''
                IMG_REGISTRY="192.144.178.98:443"
                IMG_NAME="my/go"
                IMG_TAG="${GIT_PREVIOUS_COMMIT}"
                IMG_FULL_NAME="${IMG_REGISTRY}/${IMG_NAME}:${IMG_TAG}"

                echo "login registry!"
                docker login -u t1 -p 'Oa123!@#' 192.144.178.98:443
                echo "IMG_TAG:${GIT_PREVIOUS_COMMIT}, build image!"
                docker build -t ${IMG_FULL_NAME} -f Dockerfile .
                echo "push image!"
                docker push ${IMG_FULL_NAME}
                echo "rmi image!"
                docekr rmi ${IMG_FULL_NAME} || true

                sed -i "s#{{IMG_NAME}}#${IMG_FULL_NAME}#g" deploy/deploy.yaml
                sed -i "s#{{APP_VERSION}}#${IMG_TAG}#g" deploy/deploy.yaml
                echo "toimges.sh ok~"
                '''
            }
        }
        stage("deploy k8s") {
            steps {
                echo "----------------------部署到k8s------------------"
                sh label:"deploy image to k8s", script: "/bin/sh deploy/sh/tok8s.sh"
            }
        }
    }
}
// [jenkins 如何发布k8s项目](http://t.zoukankan.com/huningfei-p-14202592.html)